# Generated by Django 5.0.1 on 2024-01-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeapp", "0003_alter_coffee_image_alter_order_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
    ]
