# Generated by Django 5.0.1 on 2024-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeapp", "0004_orderitem_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
