# Generated by Django 5.0.1 on 2024-01-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeapp", "0005_remove_orderitem_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="image",
            field=models.CharField(max_length=2550),
        ),
    ]
